### ISSUE TITLE
Clicking permalink, then synergies does not behave as expected

### ISSUE THREAD

**Issue by elistevens** [randolphw/doop#1]
Firefox 36.0.1, OSX.

http://randolphw.github.io/doop/?basqM,dQ,c21,WV,YD1,Pr,qi2:phyGS2,i6,SD,mh:melGS2,46,XF,0:areGS2,0,0,0:dot8E1,0,0,0:movGS2,0,0,0:bosGS2,0,0,0:unaeC2,0,0,0:SP_GDC,oE:TN_Cr1,-Q:equD,6,B,5:syn3,F,K,N,O,R,a,c,f,i:cos5,6,7,8

I click Synergies, and see the following (as expected):

![screen shot 2015-03-10 at 10 35 06 am](https://cloud.githubusercontent.com/assets/138016/6581032/8fd37d06-c711-11e4-9b13-80c0704320db.png)

After a single left click on Moon Knight, I see:

![screen shot 2015-03-10 at 10 35 30 am](https://cloud.githubusercontent.com/assets/138016/6581055/aba37586-c711-11e4-96c4-a8d7f15cfff9.png)

I don't believe this is intended behavior.

**Comment by randolphw** [comment]
This was actually intended behavior (modal sorting), but I can see that it's confusing. Synergy dps display/sort logic has been changed.
